version: '3.4'

services:
  mongoclient:
    container_name: mongoclient
    restart: always
    ports:
      - "3000:3000"
    volumes:
     - mongoclient_data:/data/db 

  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9000:9000" 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
        - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  catalog.db:
    container_name: catalog.db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  basket.db:
    container_name: basket.db
    restart: always
    ports:
      - "6379:6379"

  discount.db:
    container_name: discount.db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    ports:
        - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  catalog.api:
    container_name: catalog.api
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=mongodb://catalog.db:27017"
    depends_on:
      - catalog.db
    ports:
      - "8000:80"

  basket.api:
    container_name: basket.api
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings__ConnectionString=basket.db:6379"
      - "GrpcSettings__DiscountUrl=http://discount.grpc"
    depends_on:
      - basket.db
    ports:
      - "8001:80"

  #discount.api:
  #  container_name: discount.api
  #  restart: always
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    - "DatabaseSettings__ConnectionString=Server=discount.db;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
  #  depends_on:
  #    - discount.db
  #  ports:
  #    - "8002:80"

  discount.grpc:
    container_name: discount.grpc
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=Server=discount.db;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
    ports:
      - "8003:80"